AllCops:
  Exclude:
    - '.git-hooks/**/*'
    - 'bin/**/*'
Style/FileName:
  Description: 'Use snake_case for source file names.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#snake-case-files'
  Enabled: false
