# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.6.3

    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "shore.gemspec" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - vendor/bundle
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}

      # Rubocop check
      - run: bundle exec rubocop

      # run tests!
      - run:
          name: run tests
          command: bundle exec rspec --format progress