version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
       - image: circleci/ruby:2.6.3
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "shore.gemspec" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - vendor/bundle
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}

      # Rubocop check
      - run: bundle exec rubocop

      # run tests!
      - run:
          name: run tests
          command: bundle exec rspec --format progress

workflows:
  version: 2.1
  build_and_test:
    - build:
      context:
        - github-auth
        - contribsys-auth
